### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OttomanDeveloper** [adhamkhaledabdelwahab/notification_listener_service#2]
I tried this plug-in and it's not working. Only Get Device Info is working at the moment.

This fork is working but it's failed to update notifications when the app is in a background state or the app is closed completely:

https://github.com/dreautall/notification_listener_service

Flutter 3.10.6
Dart 3.0.6.

Platform Android

**Comment by adhamkhaledabdelwahab** [comment]
thanks for you review I'm gonna check it out

**Comment by OttomanDeveloper** [comment]
This fork is working but it's failed to update notifications when the app is in a background state or the app is closed completely:

https://github.com/dreautall/notification_listener_service

**Comment by adhamkhaledabdelwahab** [comment]
Hello, I have reviewed your issue and found that the plugin is working well even in the background but this plugin is used to listen to local notification not remote remember this one
